# This file contains config used for each device

# node_id:        The id of the name
# node_name:      The of the node, also used in sensor names
# encryption_key: A key used for encrypting the api
# password:       This password is used for the api, ap, ota, and web_server
# wifi_ssid:      The ssid name of the wifi network
# wifi_password:  The password of the wifi network

esphome:
  name: $node_id

logger:
  level: DEBUG

api:
  encryption:
    key: $encryption_key

ota:
  password: $password

wifi:
  ssid: $wifi_ssid
  password: $wifi_password

  ap:
    ssid: $node_name Fallback
    password: $password

captive_portal:

web_server:
  port: 80
  auth:
    username: admin
    password: $password
