# mqtt_broker:    The adress of the broker
# mqtt_username:  The username of the broker
# mqtt_password:  The password of the broker

mqtt:
  broker: $mqtt_broker
  username: $mqtt_username
  password: $mqtt_password
  discovery: false
  topic_prefix: esphome/$node_id
