text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${node_name} IP Address
    ssid:
      name: ${node_name} Wi-Fi SSID
    bssid:
      name: ${node_name} Wi-Fi BSSID
    mac_address:
      name: ${node_name} Wi-Fi MAC
