packages:
  i2c: github://wjtje/esphome-config/config/common/communication_buses/i2c.yaml@main

sensor:
  - platform: aht10
    temperature:
      name: Temperature
      id: device_temperature
    humidity:
      name: Humidity
      id: device_humidity
    update_interval: 30s
