# node_location: The location of the node

packages:
  i2c: github://wjtje/esphome-config/config/common/communication_buses/i2c.yaml@main

sensor:
  - platform: bme280
    update_interval: 30s
    address: 0x76
    temperature:
      name: $node_location Temperature
      id: device_temperature
    pressure:
      name: $node_location Pressure
      id: device_pressure
    humidity:
      name: $node_location Humidity
      id: device_humidity
  - platform: template
    name: $node_location Altitude
    lambda: |-
      const float STANDARD_SEA_LEVEL_PRESSURE = 1013.25; //in hPa, see note
      return ((id(device_temperature).state + 273.15) / 0.0065) *
        (powf((STANDARD_SEA_LEVEL_PRESSURE / id(device_pressure).state), 0.190234) - 1); // in meter
    update_interval: 30s
    icon: 'mdi:signal'
    unit_of_measurement: 'm'
  - platform: template
    name: $node_location Absolute Humidity
    lambda: |-
      const float mw = 18.01534;    // molar mass of water g/mol
      const float r = 8.31447215;   // Universal gas constant J/mol/K
      return (6.112 * powf(2.718281828, (17.67 * id(device_temperature).state) /
        (id(device_temperature).state + 243.5)) * id(device_humidity).state * mw) /
        ((273.15 + id(device_temperature).state) * r); // in grams/m^3
    accuracy_decimals: 2
    update_interval: 30s
    icon: 'mdi:water'
    unit_of_measurement: 'g/m³'
  - platform: template
    name: $node_location Dew Point
    lambda: |-
      return (243.5*(log(id(device_humidity).state/100)+((17.67*id(device_temperature).state)/
      (243.5+id(device_temperature).state)))/(17.67-log(id(device_humidity).state/100)-
      ((17.67*id(device_temperature).state)/(243.5+id(device_temperature).state))));
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'
    update_interval: 30s
