# node_location: The location of the node

packages:
  i2c: github://wjtje/esphome-config/config/common/communication_buses/i2c.yaml@main

sensor:
  - platform: bme280
    update_interval: 30s
    address: 0x76
    temperature:
      name: $node_location Temperature
    pressure:
      name: $node_location Pressure
    humidity:
      name: $node_location Humidity
