# node_id:            The id of the name
# node_name:          The of the node, also used in sensor names
# encryption_key:     A key used for encrypting the api
# ota_password:       This password is used for the ota
# password:           This password is used for the AP and web interface
# wifi_ssid:          The ssid name of the wifi network
# wifi_password:      The password of the wifi network
# direct_mode:        The inital value for the direct mode option
# double_toggle:      The inital value for the double toggle option
# double_toggle_time: The inital toggle speed for the double toggle option
# relay_restore_mode: The way the relay is restored when the chip is restarted

# Define the chip
esp8266:
  board: esp8285

script:
  - id: on_switch_toggle
    mode: restart
    parameters:
      button_id: int
      direct_mode: bool
      double_toggle: bool
      double_toggle_time: float
    then:
      - if:
          condition:
            lambda: return double_toggle;
          then: # Dubble toggle mode
            # Display a log mesage
            - logger.log:
                format: "Called 'on_switch_toggle' with (%i, %i, %f)"
                args:
                  - button_id
                  - double_toggle
                  - double_toggle_time
            # Check if it's the same button
            - lambda: |-
                if (id(s_button_id) != button_id && id(s_button_id) != 255) 
                  // Execute event handler for old button_id
                  id(switch_event_handler)->execute(id(s_button_id), id(s_direct_mode), id(s_toggle_amount));
                // Update count
                if (id(s_button_id) == button_id) {
                  id(s_toggle_amount) += 1;
                } else {
                  // First time (setup global)
                  id(s_button_id) = button_id;
                  id(s_direct_mode) = direct_mode;
                  id(s_toggle_amount) = 0;
                }
            # Delay toggle time
            - delay: !lambda "return double_toggle_time * 1000;"
            # Check if this is the correct one
            - lambda: |-
                id(switch_event_handler)->execute(button_id, direct_mode, id(s_toggle_amount));
                // Reset globals
                id(s_button_id) = 255;
          else: # Single toggle mode
            - lambda: |-
                id(switch_event_handler)->execute(button_id, direct_mode, 0);
  - id: switch_event_handler
    mode: parallel
    parameters:
      button_id: int
      direct_mode: bool
      toggle_count: int
    then:
      # Display a log mesage
      - logger.log:
          format: "Toggled button %i %i time(s)"
          args:
            - button_id
            - toggle_count
      # Check if direct mode is enabled or not connected
      - if:
          condition:
            and:
              - or:
                  - not:
                      api.connected:
                  - lambda: |-
                      return direct_mode;
              - lambda: |-
                  return toggle_count == 0;
          then:
            - switch.toggle:
                id: relay_1
      # Send event to home assistant
      - if:
          condition:
            lambda: |-
              return toggle_count == 0;
          then:
            - homeassistant.event:
                event: esphome.sonoff_single_toggle
                data:
                  node_id: $node_id
                data_template:
                  button_id: "{{ button_id }}"
                variables:
                  button_id: !lambda "return button_id;"
      - if:
          condition:
            lambda: |-
              return toggle_count == 1;
          then:
            - homeassistant.event:
                event: esphome.sonoff_double_toggle
                data:
                  node_id: $node_id
                data_template:
                  button_id: "{{ button_id }}"
                variables:
                  button_id: !lambda "return button_id;"
      - homeassistant.event:
          event: esphome.sonoff_toggle
          data:
            node_id: $node_id
          data_template:
            button_id: "{{ button_id }}"
            toggle_amount: "{{ toggle_amount }}"
          variables:
            button_id: !lambda "return button_id;"
            toggle_amount: !lambda "return toggle_count;"

# Define the two default outputs
output:
  - id: relay_ouput
    platform: gpio
    pin: GPIO12

binary_sensor:
  # The internal push button
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay_1
  # The external switch
  - platform: gpio
    name: Switch
    pin: GPIO04
    id: switch_0
    filters:
      - invert:
      - delayed_off: 10ms
    on_state:
      then:
        - script.execute:
            id: on_switch_toggle
            button_id: 0
            direct_mode: !lambda "return id(g_direct_mode);"
            double_toggle: !lambda "return id(g_double_toggle);"
            double_toggle_time: !lambda "return id(double_toggle_time).state;"

light:
  # Red LED
  - platform: status_led
    name: Red LED
    pin:
      number: GPIO13
      inverted: true
    internal: true

globals:
  - id: g_direct_mode
    type: bool
    initial_value: $direct_mode
  - id: g_double_toggle
    type: bool
    initial_value: $double_toggle
  - id: s_button_id
    type: int
    initial_value: '255'
  - id: s_direct_mode
    type: bool
    initial_value: 'false'
  - id: s_toggle_amount
    type: int
    initial_value: '0'


number:
  # The toggle time that counts as a toggle
  - platform: template
    name: Double Toggle Time
    id: double_toggle_time
    entity_category: config
    icon: mdi:cog-transfer
    unit_of_measurement: s
    optimistic: true
    min_value: 0
    max_value: 1
    initial_value: $double_toggle_time
    step: 0.05

switch:
  # The internal relay
  - platform: output
    name: Relay
    icon: mdi:lightning-bolt
    output: relay_ouput
    restore_mode: $relay_restore_mode
    id: relay_1
  # Configuration for internal automatisation
  - platform: template
    name: Direct Mode
    entity_category: config
    icon: mdi:cog-transfer
    lambda: |-
      return id(g_direct_mode);
    restore_mode: DISABLED
    turn_on_action:
      - globals.set:
          id: g_direct_mode
          value: "true"
    turn_off_action:
      - globals.set:
          id: g_direct_mode
          value: "false"
  # Configuration for the double toggle fuction
  - platform: template
    name: Double Toggle
    entity_category: config
    icon: mdi:cog-transfer
    lambda: |-
      return id(g_double_toggle);
    restore_mode: DISABLED
    turn_on_action:
      - globals.set:
          id: g_double_toggle
          value: "true"
    turn_off_action:
      - globals.set:
          id: g_double_toggle
          value: "false"